### ISSUE TITLE
能否写个PHP版本/另可以自动集成评测机？

### ISSUE THREAD

**Issue by oier-jyb666** [YuFengZe/OnlineIde#1]
RT

**Comment by YuFengZe** [comment]
Q1：之前写过一个php版本，不小心把服务器清空了，代码就丢了，没设置备份没办法回滚。相比之下，php其实不如python的django框架好用，特别是安全性这一块，php的安全性我无法保证。如果您是因为django的安装或者使用有问题，我可以帮助您。如果是不会使用python语言，可以直接安装使用我的项目。如果有期望的功能，可以提出，我会尽力增加。

Q2：我的项目是基于青岛大学的开源OnlineJudge，您可以直接使用她的在线oj。另外，我没看明白您的“自动集成评测机”是什么意思？

**Comment by oier-jyb666** [comment]
感谢，已自己用PHP+websocket实现了IDE

http://1.116.217.97/ide/ （话说您的网站支持注册吗？）

**Comment by YuFengZe** [comment]
php+websocket的话需要注意安全性问题，是否使用了运行沙箱？如果有非法的文件读入可能会造成服务器损害。
我的ide使用的是mysql数据库，建立之初的目的就是供我自己和认识的人使用，没有开放的打算，所以没有开设注册页面。所有的账号均由我从mysql的管理器phpmyadmin进行管理。

**Comment by oier-jyb666** [comment]
感谢，能否指导下沙箱的使用，现在打算使用docker

**Comment by YuFengZe** [comment]
您好，我使用的是青岛大学的运行沙箱，但是他的一些功能不太完善，我的ide对他进行了一个在封装，并开放了api，您可以部署青岛大学的沙箱后，部署我的ide，并开启api，再使用您的ide调用我的ide的api即可。

**Comment by YuFengZe** [comment]
我的ide已经完全重写，示例：ide.yufengze.org 可以通过一句命令直接部署，不需要多余配置
```
wget https://www.yufengze.org/download/onlineide/install.cn.sh && sh install.cn.sh
```
