### ISSUE TITLE
使用安装脚本无法正常加载static里的资源

### ISSUE THREAD

**Issue by yuruxuan** [YuFengZe/OnlineIde#2]
测试环境：
腾讯云 Ubuntu 20 64bit

步骤：
sudo sh install.cn.sh
安装完成后，chrome无法加载static目录下的资源，js和css全部都404

**Comment by YuFengZe** [comment]
static目录下储存了编辑器的所有文件，我没有把它开源而是需要在安装时通过npm安装。
请检查static目录下是否存在node_modules文件，如果存在，请检查node_modules下是否存在monaco-editor文件。
如果不存在，请进入static目录并执行
```
npm install  monaco-editor
```

**Comment by YuFengZe** [comment]
你好~解决了嘛？？
